import Testing

@testable import ClipboardCapture

@Suite("Capture policy")
struct CapturePolicyTests {
  @Test("rejects every protected marker class")
  func rejectsProtectedMarkers() {
    let policy = CapturePolicy()
    let cases: [(String, CaptureSkipReason)] = [
      (PasteboardTypeIdentifier.ownWrite, .ownWrite),
      (PasteboardTypeIdentifier.concealed, .concealed),
      ("com.agilebits.onepassword", .concealed),
      (PasteboardTypeIdentifier.transient, .transient),
      ("de.petermaurer.TransientPasteboardType", .transient),
      (PasteboardTypeIdentifier.autoGenerated, .autoGenerated),
    ]

    for (type, reason) in cases {
      let decision = policy.preflight(
        metadata: PasteboardMetadata(
          changeCount: 1,
          typeIdentifiers: [type, PasteboardTypeIdentifier.plainText]
        ),
        configuration: CaptureConfiguration(isEnabled: true)
      )
      #expect(decision == .skip(reason))
    }
  }

  @Test("fails closed when pasteboard access is denied")
  func rejectsDeniedAccess() {
    let decision = CapturePolicy().preflight(
      metadata: PasteboardMetadata(
        changeCount: 1,
        typeIdentifiers: [PasteboardTypeIdentifier.plainText],
        accessState: .denied
      ),
      configuration: CaptureConfiguration(isEnabled: true)
    )

    #expect(decision == .skip(.accessDenied))
  }
}
