import ClipDomain
import Foundation

public struct CaptureConfiguration: Equatable, Sendable {
  public var isEnabled: Bool
  public var isPaused: Bool
  public var ignoredBundleIdentifiers: Set<String>
  public var maximumTextBytes: Int
  public var maximumImageBytes: Int
  public var maximumImagePixels: Int
  public var imagePreflightTimeoutSeconds: Double

  public init(
    isEnabled: Bool = false,
    isPaused: Bool = false,
    ignoredBundleIdentifiers: Set<String> = [],
    maximumTextBytes: Int = 5 * 1_024 * 1_024,
    maximumImageBytes: Int = 25 * 1_024 * 1_024,
    maximumImagePixels: Int = 40_000_000,
    imagePreflightTimeoutSeconds: Double = 10
  ) {
    self.isEnabled = isEnabled
    self.isPaused = isPaused
    self.ignoredBundleIdentifiers = Set(ignoredBundleIdentifiers.map { $0.lowercased() })
    self.maximumTextBytes = maximumTextBytes
    self.maximumImageBytes = maximumImageBytes
    self.maximumImagePixels = maximumImagePixels
    self.imagePreflightTimeoutSeconds = imagePreflightTimeoutSeconds
  }
}

public enum CaptureSkipReason: Equatable, Sendable {
  case disabled
  case paused
  case ignoredNextCopy
  case inconsistentSnapshot
  case accessDenied
  case ownWrite
  case concealed
  case transient
  case autoGenerated
  case ignoredApplication
  case unsupportedType
  case emptyText
  case emptyImage
  case unreadableImage
  case tooLarge
  case sensitiveContent
  case preflightTimeout
}

public enum CapturePreflightDecision: Equatable, Sendable {
  case allowText(ClipSource?)
  case allowImage(ClipSource?)
  case skip(CaptureSkipReason)
}

public struct CapturePolicy: Sendable {
  public init() {}

  public func preflight(
    metadata: PasteboardMetadata,
    configuration: CaptureConfiguration
  ) -> CapturePreflightDecision {
    guard configuration.isEnabled else { return .skip(.disabled) }
    guard !configuration.isPaused else { return .skip(.paused) }
    guard metadata.accessState != .denied else { return .skip(.accessDenied) }

    let types = metadata.typeIdentifiers
    if types.contains(PasteboardTypeIdentifier.ownWrite) { return .skip(.ownWrite) }
    if types.contains(PasteboardTypeIdentifier.concealed)
      || !types.isDisjoint(with: PasteboardTypeIdentifier.concealedVendorTypes)
    {
      return .skip(.concealed)
    }
    if types.contains(PasteboardTypeIdentifier.transient)
      || !types.isDisjoint(with: PasteboardTypeIdentifier.transientVendorTypes)
    {
      return .skip(.transient)
    }
    if types.contains(PasteboardTypeIdentifier.autoGenerated) { return .skip(.autoGenerated) }

    let sourceBundleIdentifiers = [
      metadata.declaredSourceBundleIdentifier,
      metadata.frontmostApplication?.bundleIdentifier,
    ].compactMap { $0?.lowercased() }
    if sourceBundleIdentifiers.contains(where: configuration.ignoredBundleIdentifiers.contains) {
      return .skip(.ignoredApplication)
    }

    let source = metadata.resolvedSource
    // Text wins on mixed snapshots: an image carrying a text flavor (e.g. a
    // copied image URL) is more useful and more searchable as text, and this
    // preserves the long-standing behavior for every existing producer.
    if types.contains(PasteboardTypeIdentifier.plainText) {
      return .allowText(source)
    }
    if !types.isDisjoint(with: PasteboardTypeIdentifier.imageTypes) {
      return .allowImage(source)
    }
    return .skip(.unsupportedType)
  }

  public func classifyText(_ text: String) -> ClipKind {
    let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
    guard !trimmed.contains(where: \.isWhitespace),
      let components = URLComponents(string: trimmed),
      let scheme = components.scheme?.lowercased(),
      ["http", "https"].contains(scheme),
      components.host?.isEmpty == false
    else {
      return .text
    }
    return .link
  }
}
