import AppKit
import ClipDomain

@MainActor
public final class NSPasteboardReader: PasteboardReading {
  private let pasteboard: NSPasteboard

  public init(pasteboard: NSPasteboard = .general) {
    self.pasteboard = pasteboard
  }

  public var changeCount: Int {
    pasteboard.changeCount
  }

  public func metadata() -> PasteboardMetadata {
    let items = pasteboard.pasteboardItems ?? []
    let typeIdentifiers = Set(items.flatMap { $0.types.map(\.rawValue) })
    let declaredSourceBundleIdentifier: String?
    if typeIdentifiers.contains(PasteboardTypeIdentifier.ownWrite)
      || typeIdentifiers.contains(PasteboardTypeIdentifier.concealed)
      || typeIdentifiers.contains(PasteboardTypeIdentifier.transient)
      || typeIdentifiers.contains(PasteboardTypeIdentifier.autoGenerated)
      || !typeIdentifiers.isDisjoint(with: PasteboardTypeIdentifier.concealedVendorTypes)
      || !typeIdentifiers.isDisjoint(with: PasteboardTypeIdentifier.transientVendorTypes)
    {
      declaredSourceBundleIdentifier = nil
    } else {
      declaredSourceBundleIdentifier =
        items.lazy.compactMap { item in
          item.string(forType: NSPasteboard.PasteboardType(PasteboardTypeIdentifier.source))
        }.first
    }

    let frontmost = NSWorkspace.shared.frontmostApplication
    let frontmostSource = ClipSource(
      bundleIdentifier: frontmost?.bundleIdentifier,
      applicationName: frontmost?.localizedName,
      provenance: .frontmostApplication
    )

    return PasteboardMetadata(
      changeCount: pasteboard.changeCount,
      typeIdentifiers: typeIdentifiers,
      declaredSourceBundleIdentifier: declaredSourceBundleIdentifier,
      frontmostApplication: frontmostSource,
      accessState: accessState
    )
  }

  public func readPlainText() -> String? {
    pasteboard.string(forType: .string)
  }

  public func readImageData() -> (data: Data, uti: String)? {
    for uti in PasteboardTypeIdentifier.imageTypesInPreferenceOrder {
      if let data = pasteboard.data(forType: NSPasteboard.PasteboardType(uti)),
        !data.isEmpty
      {
        return (data, uti)
      }
    }
    return nil
  }

  private var accessState: PasteboardAccessState {
    guard #available(macOS 15.4, *) else { return .allowed }
    switch pasteboard.accessBehavior {
    case .default: return .notDetermined
    case .ask: return .ask
    case .alwaysAllow: return .allowed
    case .alwaysDeny: return .denied
    @unknown default: return .notDetermined
    }
  }
}
