import ClipDomain
import Foundation

public enum PasteboardTypeIdentifier {
  public static let plainText = "public.utf8-plain-text"
  public static let png = "public.png"
  public static let tiff = "public.tiff"
  public static let jpeg = "public.jpeg"
  public static let fileURL = "public.file-url"
  public static let concealed = "org.nspasteboard.ConcealedType"
  public static let transient = "org.nspasteboard.TransientType"
  public static let autoGenerated = "org.nspasteboard.AutoGeneratedType"
  public static let source = "org.nspasteboard.source"
  public static let ownWrite = "io.github.imrajyavardhan12.copyloom.internal"

  /// Accepted image flavors in read-preference order.
  public static let imageTypesInPreferenceOrder = [png, tiff, jpeg]

  public static var imageTypes: Set<String> {
    Set(imageTypesInPreferenceOrder)
  }

  static let concealedVendorTypes: Set<String> = [
    "com.agilebits.onepassword",
    "net.antelle.keeweb",
  ]

  static let transientVendorTypes: Set<String> = [
    "com.typeit4me.clipping",
    "de.petermaurer.TransientPasteboardType",
    "Pasteboard generator type",
  ]
}

public enum PasteboardAccessState: Equatable, Sendable {
  case notDetermined
  case ask
  case allowed
  case denied
}

public struct PasteboardMetadata: Equatable, Sendable {
  public let changeCount: Int
  public let typeIdentifiers: Set<String>
  public let declaredSourceBundleIdentifier: String?
  public let frontmostApplication: ClipSource?
  public let accessState: PasteboardAccessState

  public init(
    changeCount: Int,
    typeIdentifiers: Set<String>,
    declaredSourceBundleIdentifier: String? = nil,
    frontmostApplication: ClipSource? = nil,
    accessState: PasteboardAccessState = .allowed
  ) {
    self.changeCount = changeCount
    self.typeIdentifiers = typeIdentifiers
    self.declaredSourceBundleIdentifier = declaredSourceBundleIdentifier
    self.frontmostApplication = frontmostApplication
    self.accessState = accessState
  }

  public var resolvedSource: ClipSource? {
    guard
      let declared = declaredSourceBundleIdentifier?
        .trimmingCharacters(in: .whitespacesAndNewlines), !declared.isEmpty
    else {
      return frontmostApplication
    }
    let matchingName =
      frontmostApplication?.bundleIdentifier?.caseInsensitiveCompare(declared) == .orderedSame
      ? frontmostApplication?.applicationName
      : nil
    return ClipSource(
      bundleIdentifier: declared,
      applicationName: matchingName,
      provenance: .declared
    )
  }
}

@MainActor
public protocol PasteboardReading: AnyObject {
  var changeCount: Int { get }
  func metadata() -> PasteboardMetadata
  func readPlainText() -> String?
  func readImageData() -> (data: Data, uti: String)?
  func readFileURLs() -> [URL]
}
